title: 'Apirak Panatkool'
tagline: 'UX Evangelist'
email: apirakb@gmail.com
image: 'https://apirak.com/assets/image/apirak@2x.jpg'
logo: 'https://apirak.com/assets/image/apirak@2x.jpg'
description: >-
  Add description here
author: Apirak Panatkool
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://apirak.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: apirak
github_username: apirak

google_analytics:
  id: G-V2L7EPCY83

sass:
  sass_dir: _sass
  style: conpressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag